workflows:
  ios-altstore:
    name: iOS para AltStore
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Dependências
        script: flutter pub get
      
      - name: Corrigir Pods e Firebase
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          
          # Adiciona post_install hook no Podfile para fixar o xcconfig
          cat >> Podfile << 'EOF'
      
      # Fix Firebase xcconfig
      post_install do |installer|
        installer.pods_project.targets.each do |target|
          flutter_additional_ios_build_settings(target)
        end
        release_xcconfig = File.join(__dir__, 'Flutter', 'Release.xcconfig')
        content = File.read(release_xcconfig)
        fix_line = "#include \"Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig\"\n"
        File.write(release_xcconfig, fix_line + content) unless content.include?('Pods-Runner.release.xcconfig')
      end
      EOF
          
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign -t lib/main.dart

      - name: Empacotar IPA
        script: |
          APP=$(find build/ios/iphoneos -name "Runner.app" -type d | head -1)
          mkdir -p Payload
          cp -r "$APP" Payload/
          zip -qr bot_autobet.ipa Payload/

    artifacts:
      - bot_autobet.ipa
