workflows:
  ios-altstore:
    name: iOS para AltStore
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Dependencias
        script: flutter pub get

      - name: Corrigir Pods e Firebase
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          python3 -c "
          hook = '''
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
            xcconfig = File.join(__dir__, 'Flutter', 'Release.xcconfig')
            content = File.read(xcconfig)
            line = \"#include \\\"Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig\\\"\\n\"
            File.write(xcconfig, line + content) unless content.include?('Pods-Runner.release')
          end
          '''
          with open('Podfile', 'a') as f:
              f.write(hook)
          "
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign -t lib/main.dart

      - name: Empacotar IPA
        script: |
          APP=$(find build/ios/iphoneos -name "Runner.app" -type d | head -1)
          mkdir -p Payload
          cp -r "$APP" Payload/
          zip -qr bot_autobet.ipa Payload/

    artifacts:
      - bot_autobet.ipa
