post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
  
  # Fix: inclui o xcconfig dos Pods no Release.xcconfig do Flutter
  xcconfig_path = File.join(__dir__, 'Flutter', 'Release.xcconfig')
  xcconfig_content = File.read(xcconfig_path)
  pods_xcconfig = 'Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'
  unless xcconfig_content.include?(pods_xcconfig)
    File.open(xcconfig_path, 'w') do |f|
      f.puts "#include \"#{pods_xcconfig}\""
      f.print xcconfig_content
    end
  end
end
